### ISSUE TITLE
请问一下，你们的 IR 部分是按照 llvm IR 用 java 重写的吗

### ISSUE THREAD

**Issue by Eric-is-good** [cabinz/cbias#1]

**Comment by cabinz** [comment]
在IR的设计上我们参考了很多LLVM IR的接口和类型架构，来保证前后端的并行开发和测试；但因为本身SysY并不需要支持完整的C特性，我们也针对自己系统的需求做了额外的设计和改造。

We took a lot of references from LLVM IR's interfaces and class architectures in the design of our IR to ensure parallel development and automation testing of the front-end and back-end. However, since SysY does not require support for the full range of C features, we also made additional designs and modifications to meet our specific needs.
